# Generated by Django 5.2 on 2025-09-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_votetransaction_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
    ]
