# Generated by Django 5.2 on 2025-04-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skillaquisition_rename_feestructure_associationfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
