# Generated by Django 5.2 on 2025-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationfee',
            name='payment_code',
            field=models.CharField(default='DUES', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillaquisition',
            name='payment_code',
            field=models.CharField(default='SKILL', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
