# Generated by Django 5.2 on 2025-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_associationfee_payment_code_payment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='session',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_for',
            field=models.CharField(blank=True, choices=[('association_fee', 'Association Fee'), ('skill_acquisition', 'Skill Acquisition')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='associationfee',
            name='payment_code',
            field=models.CharField(default='DUES', max_length=4),
        ),
        migrations.AlterField(
            model_name='associationfee',
            name='session',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skillaquisition',
            name='payment_code',
            field=models.CharField(default='SKIL', max_length=4),
        ),
        migrations.AlterField(
            model_name='skillaquisition',
            name='skill_type',
            field=models.CharField(max_length=50),
        ),
    ]
