# Generated by Django 5.2 on 2025-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_payment_content_type_remove_payment_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationfee',
            name='payment_code',
            field=models.CharField(default='COLL', max_length=4),
        ),
    ]
