# Generated by Django 5.2 on 2025-04-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_newuser_options_remove_newuser_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='mat_no',
        ),
    ]
